name: 'ela_dp'
version: '1.0.0'
profile: 'ela_dp'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ela_dp:
    lake:
      spotify:
        +schema: "dp_lake_spotify_{{ target.name }}"
        +tags: ["spotify"]
    hub:
      +schema: "dp_hub_{{ target.name }}"
      music:
        staging:
          +materialized: view
        service:
          +materialized: incremental
    product:
      +schema: "dp_product_{{ target.name }}"
