name: 'ela_dp'
version: '1.0.0'
profile: 'ela_dp'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ela_dp:
    lake:
      spotify:
        +schema: "dp_lake_spotify_{{ target.name }}"
        +tags: ["spotify"]
      spotify_legacy:
        +schema: "dp_lake_spotify_{{ target.name }}"
        +tags: ["spotify"]
      garmin:
        +schema: "dp_lake_garmin_{{ target.name }}"
        +tags: ["garmin"]
    hub:
      +schema: "dp_hub_{{ target.name }}"
      utils:
        +materialized: view
      music:
        staging:
          +materialized: view
        service:
          +materialized: incremental
      activities:
        staging:
          +materialized: view
        service:
          +materialized: incremental
    product:
      +schema: "dp_product_{{ target.name }}"
      webapp:
        +schema: "dp_product_webapp_{{ target.name }}"
        +tags: ["webapp"]
      data4agent:
        +schema: "dp_product_data4agent_{{ target.name }}"
        +materialized: table
        +tags: ["garmin", "data4agent"]
